### ISSUE TITLE
why is it slow to generate xsl file ? -  can i bypass if it is already created

### ISSUE THREAD

**Issue by wanao-dc** [OP-TED/eforms-notice-viewer#40]
Hello,

To generate xml to html, it's very long. about 1 min.
I saw in log file that the creation of .xsl file take the most of the time.

My question : How can i do to make it quicker ?
If 1.xsl or 19.xsl or ...xsl is already created, can i use the old instead of creating another each time i want to view an xml in html ?

Thank you for your answer,

Didier

**Comment by rouschr** [comment]
According to a previous analysis we did it was indeed the XSL generation which was slow.
We have some internal tickets about this but currently our focus is on the SDK and (especially for me) the editor demo "save notice to XML" feature.

**Comment by rousso** [comment]
Hi @wanao-dc,

The answer to your question is simple: You do not need to translate on demand. :)

You convert the EFX files to XSL once and then use them when you need them,
There is no reason to translate again and again and again for each XML that you want to render. 

Just translate once, after you download the SDK, store them in a folder and use them when you need them.
You only need to translate once per version of the SDK. Template translation is deterministic :)

Keep the translated files in a folder and name the folder by using the major and minor version numbers of the SDK only.
So, for example: 
- Download SDK 1.3.2
- Translate all EFX files to XSL (or whatever template language you want)
- Store the translated files in a folder called `1.3` (or `XSL-1.3`, or `eforms-sdk-1.3` or something like that).
- When you need to visualise a notice, then take the proper XSL from that folder and apply it to the XML.
 To select the correct XSL for a particular notice XML, you need to first determine the correct folder where the XSL file is stored by looking at the `cbc:CustomizationID` element in the XML which tells you the version number of the SDK that was used to create that notice. You also need to look at the `cbc:SubTypeCode` element to find the proper XSL file in that folder.
- When SDK 1.3.3 is released, then download it, translate again and overwrite the files in the `1.3` folder.
- When SDK 1.4.0 is released then download it, translate again and store the files in the `1.4` folder.
- And so on....

Remember, the notice viewer is a sample application that was only built to demonstrate the concept. 
It was not built for speed :)
We may add this "pre-translation" feature in a future version of the notice viewer but for the moment we have more pressing things that need out attention.

I hope this helps.
Yannis

**Comment by wanao-dc** [comment]
Hi @rousso 

Thank you for your answer,
You really help me to understand how it works and what can i do.

I understand  that you have many other things to do before .

Didier
