### ISSUE TITLE
running eforms-notice-viewer-0.8.0-SNAPSHOT-app.jar thows error

### ISSUE THREAD

**Issue by MichaelAdam-AKA-Mike** [OP-TED/eforms-notice-viewer#72]
After downloading sdk1.7.0 is now working, another error is thrown running java -jar D:\eForms-SDK\eforms-notice-viewer-develop\target\eforms-notice-viewer-0.8.0-SNAPSHOT-app.jar de cn23.xml

The cn23.xml file is copied from downloaded eforms-sdk\1.7\examples\notices directory.
the output is:
Error at char 19 in expression in xsl:variable/@select on line 7 column 257
  FODC0005  URIs using protocol file are not permitted
at variable labels on line 7 column 257
     invoked by global variable labels at #7
at template block01 on line 162 column 34
     invoked by xsl:call-template at #139
     invoked by xsl:for-each at #138
  In template rule with match="/" on line 132 of
Error executing the application with arguments [[de, cn_23.xml]]. Please see the logs.

Log file is attatched.

[eforms-notice-viewer.log](https://github.com/OP-TED/eforms-notice-viewer/files/11914943/eforms-notice-viewer.log)

**Comment by justinasdauksa** [comment]
Any news on this issue? I am having the same problem with both sdk-1.0.0 and sdk-1.5.0

**Comment by jesperkonincks** [comment]
Also having the same issue

**Comment by rousso** [comment]
Thank you, We will look into this asap.

**Comment by jesperkonincks** [comment]
Don't know if it is of any use but the API (https://viewer.ted.europa.eu/swagger-ui/index.html#/notice-render-controller/renderNotice) throws an 500 error

**Comment by rousso** [comment]
Hi @MichaelAdam-AKA-Mike, @justinasdauksa, @jesperkonincks.
Do you still have this problem with version 0.9.0?

**Comment by jesperkonincks** [comment]
> Hi @MichaelAdam-AKA-Mike, @justinasdauksa, @jesperkonincks. Do you still have this problem with version 0.9.0?

It is working again.

**Comment by rousso** [comment]
It seems like this is not an issue in versions after 0.9.0, so I am closing this ticket.
