### ISSUE TITLE
Available in Python?

### ISSUE THREAD

**Issue by chatgptguru** [OP-TED/eforms-notice-viewer#80]
Hello, I am using eForms XML data from Doffin API. 
But May I know if therer is any way to convert that XML to HTML using Python? 
Thank you.

**Comment by bertrand-lorentz** [comment]
This question might be better suited for the forum at https://github.com/OP-TED/eForms-SDK/discussions, where other people using eForms can also contribute.

This is not an issue related to the "eforms-notice-viewer" sample application, so I'm closing this.
