### ISSUE TITLE
add params to the command line for choosing the destination filename

### ISSUE THREAD

**Issue by wanao-jd** [OP-TED/eforms-notice-viewer#81]
actually the output file is generated in  the directory build\output-html\<NoticeSubTypeCode>.html

it is better if we could choose the destination filename like this
java -jar eforms-notice-viewer-<version>-app.jar -i summary en eforms-sdk/1.0/examples/notices/cn_24_minimal.xml -d d:\desttination\myfile.html

**Comment by ciocan** [comment]
+1

**Comment by rousso** [comment]
Hi @wanao-jd, @ciocan 

This is a sample application, and its purpose is to demonstrate how to use the SDK and the EFX Toolkit to visualise a notice. 
Although we agree that the feature you propose would be nice to have, we need to maintain our focus in the current priorities, so I cannot make any promises for this one right now.

It seems like an easy thing to implement though. Any chance either of you implements this and sends us a pull-request? 
We will be happy to review it and merge it!

Thank you for your understanding,
Yannis

cc: @bertrand-lorentz
