### ISSUE TITLE
Compilation failure in eforms-notice-viewer 0.10.0 due to missing dependency

### ISSUE THREAD

**Issue by skyazid** [OP-TED/eforms-notice-viewer#86]
Hi,

I'm encountering an issue while compiling the eForms Notice Viewer (0.10.0). The build process fails due to a missing dependency. Below is the detailed error log:

[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< eu.europa.ted.eforms:eforms-notice-viewer >--------------
[INFO] Building eForms Notice Viewer 0.10.0
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/eu/europa/ted/eforms/efx-toolkit-java/2.0.0-alpha.2/efx-toolkit-java-2.0.0-alpha.2.pom
[WARNING] The POM for eu.europa.ted.eforms:efx-toolkit-java:jar:2.0.0-alpha.2 is missing, no dependency information available
Downloading from central: https://repo.maven.apache.org/maven2/eu/europa/ted/eforms/efx-toolkit-java/2.0.0-alpha.2/efx-toolkit-java-2.0.0-alpha.2.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.863 s
[INFO] Finished at: 2023-12-11T17:15:20+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project eforms-notice-viewer: Could not resolve dependencies for project eu.europa.ted.eforms:eforms-notice-viewer:jar:0.10.0: Could not find artifact
 eu.europa.ted.eforms:efx-toolkit-java:jar:2.0.0-alpha.2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

It seems that the project is unable to find the required artifact `eu.europa.ted.eforms:efx-toolkit-java:jar:2.0.0-alpha.2`. I have checked Maven Central, and it appears that this particular version of the dependency is not available. 

Thank you.

**Comment by bertrand-lorentz** [comment]
I guess you are trying to compile from the branch release/0.10.0.
Version 0.10.0 has not been released yet, because we are waiting for the dependencies to be available on Maven Central, in particular efx-toolkit-java version 2.0.0-alpha.2.

Please try again later, when the release is completed. When it is the case, you will see the corresponding tag, and the release notes on https://github.com/OP-TED/eforms-notice-viewer/releases

**Comment by skyazid** [comment]
ok thanks for your answer :)
